#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Apr 22 12:49:47 IST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=BSL_v8.4.02.2.zip
