#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Apr 20 09:08:29 IST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=6
shaderPack=BSL_v8.4.02.2.zip
